### PR TITLE
Mark 0

### PR DESCRIPTION
**Pull request by jrans**
## THIS PR

README says it all tbh but basically first attempt at modularising the db part of our abase ideas. 

Most of this code has already been added to abase master so copying it out and making it more accessible. 

The bits that need to be reviewed therefore are how the api is exposed and plugin setup but actual SQL gen and base handlers the same. 

Resolves: #2
Resolves: #3
Resolves: #5 
Resolves: #6 
Resolves: #7 
Resolves: #8 
Resolves: #9 
Resolves: #10 
Resolves: #11

### CODE REVIEW

**Comment by nelsonic** [comment]
@jrans does https://github.com/air-supply/alpha/pull/56 depend on this?

**Comment by jrans** [comment]
@nelsonic yes! But its published on npm already...

**Comment by jrans** [comment]
@eliascodes @SimonLab @shouston3 @jackcarlisle  tagging you here to have a look comment too! Be really cool if you guys started using in your projects and improving! ALso getting the other modules working, i.e. validation, view.. would be cool too and then to sort out the mother module...

**Comment by eliasmalik** [comment]
@jrans looks good. Still got the `#joi-postgresql` header in the README though, is that on purpose?

**Comment by samhstn** [comment]
@jrans Great read, loving the clean, dry, es5 code and lack of dependencies.

Sorry for being pedantic, but could you just clarify the use of the `Object.assign`.

I thought that we were not using that syntax (at least from my interpretation of this goodparts [issue](https://github.com/dwyl/goodparts/issues/221))

...but that line isn't failing your linter despite having `ecmaVersion: 5` in your `.eslintrc`

**Comment by jrans** [comment]
@eliascodes yes not sure whats happening with the repo name so left it...
@shouston3 aha must of slipped in! Yes linter doesn't pick it up. Will make the fix soon..

**Comment by nelsonic** [comment]
@jrans can I _merge_ this PR into `master` so people who see this repo have _something_ to look at?

**Comment by jrans** [comment]
@nelsonic yes that would be really cool, if all is good with you! Now that there is the base, it has been really easy to iterate features with just a couple of extra lines of code so we can quite quickly make changes when needed!

**Comment by nelsonic** [comment]
merging. 🎉

**Pull request merged**
